apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-acpi
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-acpi
    app.kubernetes.io/part-of: devfile-sample
    app.kubernetes.io/version: devel
  name: devfile-sample-acpi
spec:
  ports:
  - name: postgres
    port: 5432
    targetPort: 0
  - port: 3001
    targetPort: 3001
  selector:
    app.kubernetes.io/instance: devfile-sample-acpi
    app.kubernetes.io/name: tekton-results-postgres
  type: NodePort
status:
  loadBalancer: {}
